dynamic-imports:
    synoliacreditline:
        - synoliacreditline/js/app/components/credit-line-checkout-component
        - synoliacreditline/js/app/components/credit-line-transition-button-component
