name: CI

on:
    push:
        branches: [ main ]
        paths-ignore:
            - README.md
    pull_request:
        paths-ignore:
            - README.md

jobs:
    analysis:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-18.04

        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.0]

        steps:
            - uses: actions/checkout@v2

            - name: Composer - Install dependencies
              run: composer install --no-progress --ignore-platform-reqs
              id: end-of-setup

            - name: GrumPHP - Run
              run: (test -f grumphp.yml && vendor/bin/grumphp run) || echo Grumphp ruleset file does not exist, skipping step
              if: always() && steps.end-of-setup.outcome == 'success'
